spring.application.name=demo
server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/memorydemo
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Reduce heap for demo purpose
# Run with:
# java -Xms128m -Xmx128m -jar app.jar